### ISSUE TITLE
integrate neutron with Dvs on vmware esxi !!! 

### ISSUE THREAD

**Issue by letrungvn** [cybercom-finland/neutron_vmware_dvswitch#4]
Hello Team,

i'm integrating opentsack  with the esxisting vmware.  my step as below:
- step1 : install openstack version kilo . as introduce at openstack website
- step2: install VMware esxi 5.1 infastructure.
- step3: the integating openstack - vmware

Now, i want to integrate Neutron with VDs, ( not through NSX plugin). At present, seem neutron not support this . 
I read your post and i can see that you have done it.
So, can you inform some information for this ? any procedure or step by step document to do it. 

Thanks you very much !

**Comment by toddnni** [comment]
Hello. Sorry for the late reply. We are not spending any more effort to the driver (see #6). Hopefully you can make it reading README.md.
